# Generated by Django 5.0 on 2024-01-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtask', '0002_medicalchart_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalchart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalchart',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='medicalchartstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalchartstatus',
            name='modified_by',
        ),
    ]
